apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "observability.open-cluster-management.io/v1beta1",
          "kind": "MultiClusterObservability",
          "metadata": {
            "name": "observability"
          },
          "spec": {
            "storageConfigObject": {
              "metricObjectStorage": {
                "key": "thanos.yaml",
                "name": "thanos-object-storage"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
  name: multicluster-observability-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MultiClusterObservability is the Schema for the multiclusterobservability
        API
      kind: MultiClusterObservability
      name: multiclusterobservabilities.observability.open-cluster-management.io
      version: v1beta1
  description: |
    The multicluster-observability-operator is a component of ACM observability feature. It is designed to install into Hub Cluster.
  displayName: Multicluster Observability Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - multicluster-observability-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - monitor.open-cluster-management.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - observability.open-cluster-management.io
          resources:
          - '*'
          - multiclusterobservabilities
          - endpointmonitorings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - core.observatorium.io
          resources:
          - observatoria
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - integreatly.org
          resources:
          - grafanas
          - grafanas/status
          - grafanas/finalizers
          - grafanadashboards
          - grafanadashboards/status
          - grafanadatasources
          - grafanadatasources/status
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - deletecollection
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - deletecollection
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          - routes/status
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - deletecollection
          - watch
          - create
        - apiGroups:
          - apps.open-cluster-management.io
          resources:
          - '*'
          - placementrules
          verbs:
          - '*'
        - apiGroups:
          - work.open-cluster-management.io
          resources:
          - '*'
          - manifestworks
          verbs:
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - '*'
          - infrastructures
          verbs:
          - '*'
        serviceAccountName: multicluster-observability-operator
      deployments:
      - name: multicluster-observability-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: multicluster-observability-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: multicluster-observability-operator
            spec:
              containers:
              - command:
                - mco-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: multicluster-observability-operator
                - name: TEMPLATES_PATH
                  value: /usr/local/manifests
                - name: SPOKE_NAMESPACE
                  value: open-cluster-management-observability
                image: quay.io/open-cluster-management/multicluster-observability-operator:0.1.0-426050808a84d6152586f3f13278ca244f1f3259
                imagePullPolicy: Always
                name: multicluster-observability-operator
                resources: {}
              serviceAccountName: multicluster-observability-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - open-cluster-management
  - MultiClusterObservability
  maintainers:
  - {}
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.1.0
