apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: observatorium
  labels:
    observability.open-cluster-management.io/name: "{{MULTICLUSTEROBSERVABILITY_CR_NAME}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      observability.open-cluster-management.io/name: "{{MULTICLUSTEROBSERVABILITY_CR_NAME}}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        observability.open-cluster-management.io/name: "{{MULTICLUSTEROBSERVABILITY_CR_NAME}}"
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - mkdir -p /storage/thanos && /usr/bin/minio server /storage
        env:
        - name: MINIO_ACCESS_KEY
          value: "{{OBJ_STORAGE_ACCESSKEY}}"
        - name: MINIO_SECRET_KEY
          value: "{{OBJ_STORAGE_SECRETKEY}}"
        image: "{{MINIO_IMG_REPO}}/minio:{{MINIO_IMG_VERSION}}"
        imagePullPolicy: "{{MULTICLUSTEROBSERVABILITY_IMAGE_PULL_POLICY}}"
        name: minio
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - mountPath: /storage
          name: storage
      imagePullSecrets:
      - name: "{{MULTICLUSTEROBSERVABILITY_IMAGE_PULL_SECRET}}"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio
