apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: observability
  name: alertmanager
  namespace: open-cluster-management
spec:
  ports:
  - name: web
    port: 9094
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: observability
    app: multicluster-observability-alertmanager
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP