
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: multicluster-observability-operator
  name: metrics-monitor
  namespace: open-cluster-management
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      name: multicluster-observability-operator
