resources:
- service.yaml

patchesStrategicMerge:
# [OCP-SSC] To enable ocp service serving certificate for webhook, uncomment all the sections with [OCP-SSC] prefix.
# patches here are for enabling the ocp service serving certificate for webhook service.
- ocp_ssc_in_webhook_service.yaml
