apiVersion: v1
kind: Service
metadata:
  name: multicluster-observability-operator-service
  namespace: open-cluster-management
  labels:
    name: multicluster-observability-operator
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    name: multicluster-observability-operator
