apiVersion: v1
data:
  grafana.ini: W2F1dGhdDQpkaXNhYmxlX2xvZ2luX2Zvcm0gPSB0cnVlDQpkaXNhYmxlX3NpZ25vdXRfbWVudSA9IHRydWUNClthdXRoLmJhc2ljXQ0KZW5hYmxlZCA9IGZhbHNlDQpbYXV0aC5wcm94eV0NCmF1dG9fc2lnbl91cCA9IHRydWUNCmVuYWJsZWQgPSB0cnVlDQpoZWFkZXJfbmFtZSA9IFgtRm9yd2FyZGVkLVVzZXINCltwYXRoc10NCmRhdGEgPSAvdmFyL2xpYi9ncmFmYW5hDQpsb2dzID0gL3Zhci9saWIvZ3JhZmFuYS9sb2dzDQpwbHVnaW5zID0gL3Zhci9saWIvZ3JhZmFuYS9wbHVnaW5zDQpwcm92aXNpb25pbmcgPSAvZXRjL2dyYWZhbmEvcHJvdmlzaW9uaW5nDQpbc2VjdXJpdHldDQphZG1pbl91c2VyID0gV0hBVF9ZT1VfQVJFX0RPSU5HX0lTX1ZPSURJTkdfU1VQUE9SVF8wMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwDQpjb29raWVfc2VjdXJlID0gdHJ1ZQ0KW3NlcnZlcl0NCmh0dHBfcG9ydCA9IDMwMDENCnJvb3RfdXJsID0gJShwcm90b2NvbClzOi8vJShkb21haW4pcy9ncmFmYW5hLw0KZG9tYWluID0gbG9jYWxob3N0DQpbdXNlcnNdDQp2aWV3ZXJzX2Nhbl9lZGl0ID0gdHJ1ZQ==
kind: Secret
metadata:
  name: grafana-config
  namespace: open-cluster-management
type: Opaque
