apiVersion: v1
kind: Service
metadata:
  labels:
    name: multicluster-observability-operator
  name: metrics-service
  namespace: open-cluster-management
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    name: multicluster-observability-operator
