apiVersion: v1
data:
  service-ca.crt: ""
kind: ConfigMap
metadata:
  annotations:
    service.alpha.openshift.io/inject-cabundle: "true"
  labels:
    alertmanager: observability
  name: alertmanager-ca-bundle
  namespace: open-cluster-management
