apiVersion: observability.open-cluster-management.io/v1beta1
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  availabilityConfig: Basic
  enableDownSampling: false
  retentionResolutionRaw: 5d
  retentionResolution5m: 14d
  retentionResolution1h: 30d
  storageSize: 50Gi
