apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-observability-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicluster-observability-operator
  template:
    metadata:
      labels:
        name: multicluster-observability-operator
    spec:
      serviceAccountName: multicluster-observability-operator
      containers:
        - name: multicluster-observability-operator
          # Replace this with the built image name
          image: quay.io/open-cluster-management/multicluster-observability-operator:0.1.0-8db1b1ed74d880dd2c92c72edd749d5cd014d831
          command:
          - multicluster-observability-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicluster-observability-operator"
            - name: TEMPLATES_PATH
              value: /usr/local/manifests
            - name: SPOKE_NAMESPACE
              value: open-cluster-management-observability
