apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: open-cluster-management-observability
spec:
  clusterSelector:
    matchExpressions:
      - {key: observability, operator: NotIn, values: [disabled]}