apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: multicluster-observability-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - multicluster-observability-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - monitor.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.open-cluster-management.io
  resources:
  - '*'
  - multiclustermonitorings
  - endpointmonitorings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - core.observatorium.io
  resources:
  - observatoria
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - grafanas
  - grafanas/status
  - grafanas/finalizers
  - grafanadashboards
  - grafanadashboards/status
  - grafanadatasources
  - grafanadatasources/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  - routes/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
  - create
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - '*'
  - placementrules
  verbs:
  - '*'
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - '*'
  - manifestworks
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - '*'
  - infrastructures
  verbs:
  - '*'
