# The following patch enables conversion webhook for CRDw
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: multiclusterobservabilities.observability.open-cluster-management.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1","v1beta1"]
      clientConfig:
        service:
          namespace: $(SERVICE_NAMESPACE)
          name: multicluster-observability-webhook-service
          path: /convert
        caBundle: XG4=
