# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiclusterobservabilities.observability.open-cluster-management.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: open-cluster-management
          name: multicluster-observability-operator-service
          port: 443
          path: /convert
