kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-whitelist
data:
  metrics_list.yaml: |
    default:
      - ALERTS
      - :node_memory_MemAvailable_bytes:sum
      - apiserver_request_count
      - apiserver_request_duration_seconds_bucket
      - apiserver_request_latencies_summary_count
      - apiserver_request_latencies_summary_sum
      - apiserver_request_total
      - cluster:capacity_cpu_cores:sum
      - cluster:capacity_memory_bytes:sum
      - cluster:container_cpu_usage:ratio
      - cluster:container_spec_cpu_shares:ratio
      - cluster:cpu_usage_cores:sum
      - cluster:memory_usage:ratio
      - cluster:memory_usage_bytes:sum
      - cluster:usage:resources:sum
      - cluster_infrastructure_provider
      - cluster_version
      - cluster_version_payload
      - container_cpu_cfs_throttled_periods_total
      - container_cpu_usage_seconds_total
      - container_fs_limit_bytes
      - container_fs_usage_bytes
      - container_memory_cache
      - container_memory_rss
      - container_memory_swap
      - container_memory_working_set_bytes
      - container_network_receive_bytes_total
      - container_network_receive_packets_dropped_total
      - container_network_receive_packets_total
      - container_network_transmit_bytes_total
      - container_network_transmit_packets_dropped_total
      - container_network_transmit_packets_total
      - etcd_helper_cache_entry_total
      - etcd_helper_cache_hit_total
      - etcd_helper_cache_miss_total
      - etcd_request_cache_get_duration_seconds_bucket
      - etcd_request_cache_add_duration_seconds_bucket
      - go_goroutines
      - haproxy_backend_connections_total
      - http_requests_total
      - instance:node_filesystem_usage:sum
      - instance:node_cpu_utilisation:rate1m
      - instance:node_load1_per_cpu:ratio
      - instance:node_memory_utilisation:ratio
      - instance:node_network_receive_bytes_excluding_lo:rate1m
      - instance:node_network_receive_drop_excluding_lo:rate1m
      - instance:node_network_transmit_bytes_excluding_lo:rate1m
      - instance:node_network_transmit_drop_excluding_lo:rate1m
      - instance:node_num_cpu:sum
      - instance:node_vmstat_pgmajfault:rate1m
      - instance_device:node_disk_io_time_seconds:rate1m
      - instance_device:node_disk_io_time_weighted_seconds:rate1m
      - kube_daemonset_status_desired_number_scheduled
      - kube_daemonset_status_number_unavailable
      - kube_deployment_status_replicas_unavailable
      - kube_node_spec_unschedulable
      - kube_node_status_allocatable_cpu_cores
      - kube_node_status_allocatable_memory_bytes
      - kube_node_status_capacity_pods
      - kube_node_status_capacity_cpu_cores
      - kube_node_status_condition
      - kube_pod_container_resource_limits_cpu_cores
      - kube_pod_container_resource_limits_memory_bytes
      - kube_pod_container_resource_requests_cpu_cores
      - kube_pod_container_resource_requests_memory_bytes
      - kube_pod_container_status_last_terminated_reason
      - kube_pod_container_status_ready
      - kube_pod_container_status_restarts_total
      - kube_pod_container_status_terminated_reason
      - kube_pod_container_status_waiting
      - kube_pod_info
      - kube_pod_status_ready
      - kube_resourcequota
      - kubelet_running_container_count
      - kubelet_runtime_operations
      - kubelet_runtime_operations_latency_microseconds
      - machine_cpu_cores
      - machine_memory_bytes
      - mixin_pod_workload
      - node_cpu_seconds_total
      - node_filesystem_avail_bytes
      - node_filesystem_free_bytes
      - node_filesystem_size_bytes
      - node_memory_MemAvailable_bytes
      - node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
      - node_namespace_pod_container:container_memory_cache
      - node_namespace_pod_container:container_memory_rss
      - node_namespace_pod_container:container_memory_swap
      - node_namespace_pod_container:container_memory_working_set_bytes
      - node_netstat_Tcp_OutSegs
      - node_netstat_Tcp_RetransSegs
      - node_netstat_TcpExt_TCPSynRetrans
      - process_cpu_seconds_total
      - process_resident_memory_bytes
      - rest_client_request_latency_seconds_bucket
      - rest_client_requests_total
      - up
      - workqueue_adds_total
      - workqueue_depth
      - workqueue_queue_duration_seconds_bucket
