resources:
# - role.yaml
# - role_binding.yaml
# - leader_election_role.yaml
# - leader_election_role_binding.yaml
# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
# - auth_proxy_service.yaml
# - auth_proxy_role.yaml
# - auth_proxy_role_binding.yaml
# - auth_proxy_client_clusterrole.yaml
#
# The following resources were addded because the rbac resources auth-generating is broken,
# so add the following resourece to make sure the mco have sufficient permissions.
- mco_role_binding.yaml
- mco_role.yaml
- mco_service_account.yaml
